version: 2

jobs:
  test_ci:
    docker:
      - image: cimg/node:lts
    working_directory: ~/Web_ToDo_API
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run tests
          command: npm run test

  deploy_ci:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FGP"
      - run:
          name: Deploy Over SSH
          command: |
            scp -r /Web_ToDo_API/* "$SSH_USER@$SSH_HOST:/var/www/"
      - run:
          name: Start PM2
          command: ssh $SSH_USER@$SSH_HOST 'pm2 start /var/www/Web_ToDo_API/index_local.js'

workflows:
  version: 2
  api_test_wf:
    jobs:
      - test_ci
      - deploy_ci:
          requires:
            - test_ci
          filters:
            branches:
              only:
                - main
