version: 2

jobs:
  test_ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run tests
          command: npm run test

  deploy_ci:
    machine:
      enabled: true
    working_directory: .
    steps:
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FGP"
      - run:
          name: Deploy Over SSH
          command: |
            scp -r . "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"

workflows:
  version: 2
  api_test_wf:
    jobs:
      - test_ci
      - deploy_ci:
          filters:
            branches:
              only:
                - main
